### ISSUE TITLE
Issue with tags as of 1.16.1 forge v32.0.108 Preventing world loading

### ISSUE THREAD

**Issue by Screw4ff** [Spalding004/fortunate_1_15#3] opened 2020-08-11 18:47 UTC
While running this mod alongside others, an issue occurs during the creation of a new world, preventing it all together. When ran without this mod, the world generates fine, when ran without it brings the player to a screen reading "data pack error, you can run in safe mode or go back to the title screen and fix this manually" where the safe mode button does nothing. When reading the log, we find the following issue here: 
[11Aug2020 11:29:07.708] [Render thread/WARN] [net.minecraft.client.Minecraft/]: Failed to load datapacks, can't proceed with server load
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Missing required tags: blocks:forge:ores,blocks:forge:ores/gold,blocks:forge:ores/iron,blocks:forge:ores/silver
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1887) ~[?:1.8.0_51]
	at net.minecraft.client.Minecraft.func_238189_a_(Minecraft.java:1808) ~[?:?]
	at net.minecraft.client.Minecraft.func_238195_a_(Minecraft.java:1660) [?:?]
	at net.minecraft.client.Minecraft.lambda$func_238195_a_$24(Minecraft.java:1664) [?:?]
	at net.minecraft.client.Minecraft$$Lambda$9479/1860965818.run(Unknown Source) [?:?]
	at net.minecraft.client.gui.screen.DatapackFailureScreen.func_238622_b_(SourceFile:28) [?:?]
	at net.minecraft.client.gui.screen.DatapackFailureScreen$$Lambda$9480/434093901.onPress(Unknown Source) [?:?]
	at net.minecraft.client.gui.widget.button.Button.func_230930_b_(SourceFile:33) [?:?]
	at net.minecraft.client.gui.widget.button.AbstractButton.func_230982_a_(SourceFile:16) [?:?]
	at net.minecraft.client.gui.widget.Widget.func_231044_a_(Widget.java:136) [?:?]
	at net.minecraft.client.gui.INestedGuiEventHandler.func_231044_a_(SourceFile:27) [?:?]
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:87) [?:?]
	at net.minecraft.client.MouseHelper$$Lambda$8517/1220432043.run(Unknown Source) [?:?]
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:421) [?:?]
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) [?:?]
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:175) [?:?]
	at net.minecraft.client.MouseHelper$$Lambda$8516/1893492120.run(Unknown Source) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(ThreadTaskExecutor.java:104) [?:?]
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:174) [?:?]
	at net.minecraft.client.MouseHelper$$Lambda$7039/1770317194.invoke(Unknown Source) [?:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) [lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) [lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(SourceFile:127) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:974) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:582) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.1-32.0.108.jar:32.0]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$435/800360816.call(Unknown Source) [forge-1.16.1-32.0.108.jar:32.0]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-6.1.1.jar:?]
Caused by: java.lang.IllegalStateException: Missing required tags: blocks:forge:ores,blocks:forge:ores/gold,blocks:forge:ores/iron,blocks:forge:ores/silver
	at net.minecraft.tags.NetworkTagManager.lambda$reload$1(NetworkTagManager.java:89) ~[?:?]
	at net.minecraft.tags.NetworkTagManager$$Lambda$9426/1857240813.accept(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51]
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?]
	at net.minecraft.resources.AsyncReloader$$Lambda$7789/1272480571.run(Unknown Source) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:172) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:134) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:150) ~[?:?]
	at net.minecraft.client.Minecraft.func_238189_a_(Minecraft.java:1807) ~[?:?]
	... 36 more[11Aug2020 11:29:07.708] [Render thread/WARN] [net.minecraft.client.Minecraft/]: Failed to load datapacks, can't proceed with server load
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Missing required tags: blocks:forge:ores,blocks:forge:ores/gold,blocks:forge:ores/iron,blocks:forge:ores/silver
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1887) ~[?:1.8.0_51]
	at net.minecraft.client.Minecraft.func_238189_a_(Minecraft.java:1808) ~[?:?]
	at net.minecraft.client.Minecraft.func_238195_a_(Minecraft.java:1660) [?:?]
	at net.minecraft.client.Minecraft.lambda$func_238195_a_$24(Minecraft.java:1664) [?:?]
	at net.minecraft.client.Minecraft$$Lambda$9479/1860965818.run(Unknown Source) [?:?]
	at net.minecraft.client.gui.screen.DatapackFailureScreen.func_238622_b_(SourceFile:28) [?:?]
	at net.minecraft.client.gui.screen.DatapackFailureScreen$$Lambda$9480/434093901.onPress(Unknown Source) [?:?]
	at net.minecraft.client.gui.widget.button.Button.func_230930_b_(SourceFile:33) [?:?]
	at net.minecraft.client.gui.widget.button.AbstractButton.func_230982_a_(SourceFile:16) [?:?]
	at net.minecraft.client.gui.widget.Widget.func_231044_a_(Widget.java:136) [?:?]
	at net.minecraft.client.gui.INestedGuiEventHandler.func_231044_a_(SourceFile:27) [?:?]
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:87) [?:?]
	at net.minecraft.client.MouseHelper$$Lambda$8517/1220432043.run(Unknown Source) [?:?]
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:421) [?:?]
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) [?:?]
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:175) [?:?]
	at net.minecraft.client.MouseHelper$$Lambda$8516/1893492120.run(Unknown Source) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(ThreadTaskExecutor.java:104) [?:?]
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:174) [?:?]
	at net.minecraft.client.MouseHelper$$Lambda$7039/1770317194.invoke(Unknown Source) [?:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) [lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) [lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(SourceFile:127) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:974) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:582) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.1-32.0.108.jar:32.0]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$435/800360816.call(Unknown Source) [forge-1.16.1-32.0.108.jar:32.0]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-6.1.1.jar:?]
Caused by: java.lang.IllegalStateException: Missing required tags: blocks:forge:ores,blocks:forge:ores/gold,blocks:forge:ores/iron,blocks:forge:ores/silver
	at net.minecraft.tags.NetworkTagManager.lambda$reload$1(NetworkTagManager.java:89) ~[?:?]
	at net.minecraft.tags.NetworkTagManager$$Lambda$9426/1857240813.accept(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51]
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?]
	at net.minecraft.resources.AsyncReloader$$Lambda$7789/1272480571.run(Unknown Source) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:172) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:134) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:150) ~[?:?]
	at net.minecraft.client.Minecraft.func_238189_a_(Minecraft.java:1807) ~[?:?]
	... 36 more
Here is the full log.
[2020-08-11-2.log](https://github.com/Spalding004/fortunate_1_15/files/5058863/2020-08-11-2.log)

When attempting to load into the previously genrated world with the mod re-installed, the world refuses to generate and we are brought to the same error screen and the log generates the same error as above.

**Comment by Spalding004** [comment] 2020-08-12 13:44
If this is indeed caused by Fortunate, it looks like forge made some changes to how data packs are read/reloaded. I’ll take a look at it if I can find the time.

You are also more than welcome to make a pull request on the 1.16.x version, listed as its own repository.

**Comment by Spalding004** [comment] 2020-09-02 03:10
This has been resolved in 2.9

**Closed as completed** 2020-09-02 03:10 UTC
Labels: bug
